# Generated by Django 2.2.9 on 2023-01-12 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0006_book_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'verbose_name': '作者表', 'verbose_name_plural': '作者表'},
        ),
        migrations.AlterModelOptions(
            name='book',
            options={'verbose_name': '图书表', 'verbose_name_plural': '图书表'},
        ),
    ]
